SET SERVEROUTPUT ON;   
CREATE OR REPLACE PROCEDURE CURSOR_EX01(VDEPTNO IN EMP.DEPTNO%TYPE)
IS
TYPE EMP_DEPT_RECORD_TYPE IS RECORD(
EMPNO EMP.EMPNO%TYPE,
ENAME EMP.ENAME%TYPE,
DNAME DEPT.DNAME%TYPE,
LOC DEPT.LOC%TYPE,
SAL EMP.SAL%TYPE);

EMP_DEPT_RECORD EMP_DEPT_RECORD_TYPE;
CURSOR C1 IS SELECT E.EMPNO, E.ENAME, D.DNAME, D.LOC, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.DEPTNO = VDEPTNO
ORDER BY E.SAL DESC;

BEGIN
DBMS_OUTPUT.PUT_LINE('사원번호/사원명/부서명/부서위치/급여');
DBMS_OUTPUT.PUT_LINE('------------------------------------------');
FOR EMP_DEPT_RECORD IN C1 LOOP
EXIT WHEN C1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(EMP_DEPT_RECORD.EMPNO||' ' ||EMP_DEPT_RECORD.ENAME||' '||EMP_DEPT_RECORD.DNAME||' '||
EMP_DEPT_RECORD.LOC||' '||EMP_DEPT_RECORD.SAL);
END LOOP;
END;
/
EXECUTE CURSOR_EX01(10);